### PR TITLE
Version 4

### PR DESCRIPTION
**Pull request by davidar**
I've [updated](https://github.com/davidar/linja-pona) the font to use OpenType features to dynamically compose compound glyphs, rather than relying on including precomposed glyphs in the font. As a result, this version allows [over 6,000 new compound glyphs](https://davidar.github.io/linja-pona/nimi) ([screenshot](https://github.com/davidar/linja-pona/blob/master/images/nimi.png)) to be used. I've also made a few other minor changes to allow linja pona to be used more easily as a webfont.

### CODE REVIEW

**Comment by brunobord** [comment]
it's looking great!
can't wait for it to be merged in master  :o)

**Comment by hommecitrons** [comment]
This is absolutely a necessary addition.

**Comment by dustinmichels** [comment]
@davidar, seems like @janSame isn't able to/interested in updating this repo. Maybe you should create a fork?

**Comment by dustinmichels** [comment]
Beautiful!

**Pull request merged**
